spring:
  application:
    name: UserCenterBackend
  session:
    timeout: 43200

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-center-main
    username: root
    password: 123456

server:
  port: 8081